// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mid1273286.Models;

#nullable disable

namespace Mid1273286.Migrations
{
    [DbContext(typeof(DressDbContext))]
    [Migration("20231001122316_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mid1273286.Models.Dress", b =>
                {
                    b.Property<int>("DressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DressId"));

                    b.Property<string>("DressName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("OnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("DressId");

                    b.ToTable("Dresses");

                    b.HasData(
                        new
                        {
                            DressId = 1,
                            DressName = "Dress 1",
                            OnSale = true,
                            Picture = "1.jpg",
                            Price = 1186.00m,
                            Size = 3
                        },
                        new
                        {
                            DressId = 2,
                            DressName = "Dress 2",
                            OnSale = true,
                            Picture = "2.jpg",
                            Price = 1818.00m,
                            Size = 3
                        },
                        new
                        {
                            DressId = 3,
                            DressName = "Dress 3",
                            OnSale = true,
                            Picture = "3.jpg",
                            Price = 1348.00m,
                            Size = 4
                        },
                        new
                        {
                            DressId = 4,
                            DressName = "Dress 4",
                            OnSale = true,
                            Picture = "4.jpg",
                            Price = 1986.00m,
                            Size = 4
                        },
                        new
                        {
                            DressId = 5,
                            DressName = "Dress 5",
                            OnSale = true,
                            Picture = "5.jpg",
                            Price = 1502.00m,
                            Size = 1
                        });
                });

            modelBuilder.Entity("Mid1273286.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<int?>("DressId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("SaleId");

                    b.HasIndex("DressId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            SaleId = 1,
                            Date = new DateTime(2022, 5, 31, 18, 23, 16, 507, DateTimeKind.Local).AddTicks(1692),
                            ProductId = 1,
                            Quantity = 190
                        },
                        new
                        {
                            SaleId = 2,
                            Date = new DateTime(2022, 5, 26, 18, 23, 16, 507, DateTimeKind.Local).AddTicks(1725),
                            ProductId = 2,
                            Quantity = 183
                        },
                        new
                        {
                            SaleId = 3,
                            Date = new DateTime(2022, 9, 9, 18, 23, 16, 507, DateTimeKind.Local).AddTicks(1733),
                            ProductId = 3,
                            Quantity = 261
                        },
                        new
                        {
                            SaleId = 4,
                            Date = new DateTime(2023, 2, 1, 18, 23, 16, 507, DateTimeKind.Local).AddTicks(1742),
                            ProductId = 4,
                            Quantity = 202
                        },
                        new
                        {
                            SaleId = 5,
                            Date = new DateTime(2022, 10, 26, 18, 23, 16, 507, DateTimeKind.Local).AddTicks(1749),
                            ProductId = 5,
                            Quantity = 182
                        },
                        new
                        {
                            SaleId = 6,
                            Date = new DateTime(2022, 12, 27, 18, 23, 16, 507, DateTimeKind.Local).AddTicks(1758),
                            ProductId = 1,
                            Quantity = 226
                        },
                        new
                        {
                            SaleId = 7,
                            Date = new DateTime(2022, 12, 4, 18, 23, 16, 507, DateTimeKind.Local).AddTicks(1766),
                            ProductId = 2,
                            Quantity = 278
                        },
                        new
                        {
                            SaleId = 8,
                            Date = new DateTime(2023, 1, 23, 18, 23, 16, 507, DateTimeKind.Local).AddTicks(1773),
                            ProductId = 3,
                            Quantity = 240
                        });
                });

            modelBuilder.Entity("Mid1273286.Models.Sale", b =>
                {
                    b.HasOne("Mid1273286.Models.Dress", "Dress")
                        .WithMany("Sales")
                        .HasForeignKey("DressId");

                    b.Navigation("Dress");
                });

            modelBuilder.Entity("Mid1273286.Models.Dress", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
